// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: suggests.proto

package dialog

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageSuggests struct {
	MessageId       *UUIDValue `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SuggestsPayload string     `protobuf:"bytes,2,opt,name=suggests_payload,json=suggestsPayload,proto3" json:"suggests_payload,omitempty"`
}

func (m *MessageSuggests) Reset()      { *m = MessageSuggests{} }
func (*MessageSuggests) ProtoMessage() {}
func (*MessageSuggests) Descriptor() ([]byte, []int) {
	return fileDescriptor_76389932d0fdfe60, []int{0}
}
func (m *MessageSuggests) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessageSuggests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessageSuggests.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MessageSuggests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSuggests.Merge(m, src)
}
func (m *MessageSuggests) XXX_Size() int {
	return m.Size()
}
func (m *MessageSuggests) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSuggests.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSuggests proto.InternalMessageInfo

func (m *MessageSuggests) GetMessageId() *UUIDValue {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *MessageSuggests) GetSuggestsPayload() string {
	if m != nil {
		return m.SuggestsPayload
	}
	return ""
}

type UpdateSuggests struct {
	Clock           int64            `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	PrevClock       int64            `protobuf:"varint,2,opt,name=prev_clock,json=prevClock,proto3" json:"prev_clock,omitempty"`
	Peer            *Peer            `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	MessageSuggests *MessageSuggests `protobuf:"bytes,4,opt,name=message_suggests,json=messageSuggests,proto3" json:"message_suggests,omitempty"`
}

func (m *UpdateSuggests) Reset()      { *m = UpdateSuggests{} }
func (*UpdateSuggests) ProtoMessage() {}
func (*UpdateSuggests) Descriptor() ([]byte, []int) {
	return fileDescriptor_76389932d0fdfe60, []int{1}
}
func (m *UpdateSuggests) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateSuggests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateSuggests.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateSuggests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSuggests.Merge(m, src)
}
func (m *UpdateSuggests) XXX_Size() int {
	return m.Size()
}
func (m *UpdateSuggests) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSuggests.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSuggests proto.InternalMessageInfo

func (m *UpdateSuggests) GetClock() int64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *UpdateSuggests) GetPrevClock() int64 {
	if m != nil {
		return m.PrevClock
	}
	return 0
}

func (m *UpdateSuggests) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *UpdateSuggests) GetMessageSuggests() *MessageSuggests {
	if m != nil {
		return m.MessageSuggests
	}
	return nil
}

type RequestLoadSuggests struct {
	FromClock int64 `protobuf:"varint,1,opt,name=from_clock,json=fromClock,proto3" json:"from_clock,omitempty"`
	Peer      *Peer `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (m *RequestLoadSuggests) Reset()      { *m = RequestLoadSuggests{} }
func (*RequestLoadSuggests) ProtoMessage() {}
func (*RequestLoadSuggests) Descriptor() ([]byte, []int) {
	return fileDescriptor_76389932d0fdfe60, []int{2}
}
func (m *RequestLoadSuggests) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestLoadSuggests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestLoadSuggests.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestLoadSuggests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLoadSuggests.Merge(m, src)
}
func (m *RequestLoadSuggests) XXX_Size() int {
	return m.Size()
}
func (m *RequestLoadSuggests) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLoadSuggests.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLoadSuggests proto.InternalMessageInfo

func (m *RequestLoadSuggests) GetFromClock() int64 {
	if m != nil {
		return m.FromClock
	}
	return 0
}

func (m *RequestLoadSuggests) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type ResponseLoadSuggests struct {
	Clock         int64              `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Suggests      []*MessageSuggests `protobuf:"bytes,2,rep,name=suggests,proto3" json:"suggests,omitempty"`
	MoreAvailable bool               `protobuf:"varint,3,opt,name=more_available,json=moreAvailable,proto3" json:"more_available,omitempty"`
}

func (m *ResponseLoadSuggests) Reset()      { *m = ResponseLoadSuggests{} }
func (*ResponseLoadSuggests) ProtoMessage() {}
func (*ResponseLoadSuggests) Descriptor() ([]byte, []int) {
	return fileDescriptor_76389932d0fdfe60, []int{3}
}
func (m *ResponseLoadSuggests) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseLoadSuggests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseLoadSuggests.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseLoadSuggests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLoadSuggests.Merge(m, src)
}
func (m *ResponseLoadSuggests) XXX_Size() int {
	return m.Size()
}
func (m *ResponseLoadSuggests) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLoadSuggests.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLoadSuggests proto.InternalMessageInfo

func (m *ResponseLoadSuggests) GetClock() int64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *ResponseLoadSuggests) GetSuggests() []*MessageSuggests {
	if m != nil {
		return m.Suggests
	}
	return nil
}

func (m *ResponseLoadSuggests) GetMoreAvailable() bool {
	if m != nil {
		return m.MoreAvailable
	}
	return false
}

type RequestLoadMessageSuggests struct {
	Peer       *Peer        `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	MessageIds []*UUIDValue `protobuf:"bytes,2,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
}

func (m *RequestLoadMessageSuggests) Reset()      { *m = RequestLoadMessageSuggests{} }
func (*RequestLoadMessageSuggests) ProtoMessage() {}
func (*RequestLoadMessageSuggests) Descriptor() ([]byte, []int) {
	return fileDescriptor_76389932d0fdfe60, []int{4}
}
func (m *RequestLoadMessageSuggests) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestLoadMessageSuggests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestLoadMessageSuggests.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestLoadMessageSuggests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLoadMessageSuggests.Merge(m, src)
}
func (m *RequestLoadMessageSuggests) XXX_Size() int {
	return m.Size()
}
func (m *RequestLoadMessageSuggests) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLoadMessageSuggests.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLoadMessageSuggests proto.InternalMessageInfo

func (m *RequestLoadMessageSuggests) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *RequestLoadMessageSuggests) GetMessageIds() []*UUIDValue {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

type ResponseLoadMessageSuggests struct {
	MessageSuggests []*MessageSuggests `protobuf:"bytes,1,rep,name=message_suggests,json=messageSuggests,proto3" json:"message_suggests,omitempty"`
}

func (m *ResponseLoadMessageSuggests) Reset()      { *m = ResponseLoadMessageSuggests{} }
func (*ResponseLoadMessageSuggests) ProtoMessage() {}
func (*ResponseLoadMessageSuggests) Descriptor() ([]byte, []int) {
	return fileDescriptor_76389932d0fdfe60, []int{5}
}
func (m *ResponseLoadMessageSuggests) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseLoadMessageSuggests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseLoadMessageSuggests.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseLoadMessageSuggests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLoadMessageSuggests.Merge(m, src)
}
func (m *ResponseLoadMessageSuggests) XXX_Size() int {
	return m.Size()
}
func (m *ResponseLoadMessageSuggests) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLoadMessageSuggests.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLoadMessageSuggests proto.InternalMessageInfo

func (m *ResponseLoadMessageSuggests) GetMessageSuggests() []*MessageSuggests {
	if m != nil {
		return m.MessageSuggests
	}
	return nil
}

type RequestSendSuggestAction struct {
	RequestId int64      `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SuggestId string     `protobuf:"bytes,2,opt,name=suggest_id,json=suggestId,proto3" json:"suggest_id,omitempty"`
	MessageId *UUIDValue `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Peer      *Peer      `protobuf:"bytes,4,opt,name=peer,proto3" json:"peer,omitempty"`
	Payload   string     `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *RequestSendSuggestAction) Reset()      { *m = RequestSendSuggestAction{} }
func (*RequestSendSuggestAction) ProtoMessage() {}
func (*RequestSendSuggestAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_76389932d0fdfe60, []int{6}
}
func (m *RequestSendSuggestAction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestSendSuggestAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestSendSuggestAction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestSendSuggestAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSendSuggestAction.Merge(m, src)
}
func (m *RequestSendSuggestAction) XXX_Size() int {
	return m.Size()
}
func (m *RequestSendSuggestAction) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSendSuggestAction.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSendSuggestAction proto.InternalMessageInfo

func (m *RequestSendSuggestAction) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *RequestSendSuggestAction) GetSuggestId() string {
	if m != nil {
		return m.SuggestId
	}
	return ""
}

func (m *RequestSendSuggestAction) GetMessageId() *UUIDValue {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *RequestSendSuggestAction) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *RequestSendSuggestAction) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageSuggests)(nil), "dialog.MessageSuggests")
	proto.RegisterType((*UpdateSuggests)(nil), "dialog.UpdateSuggests")
	proto.RegisterType((*RequestLoadSuggests)(nil), "dialog.RequestLoadSuggests")
	proto.RegisterType((*ResponseLoadSuggests)(nil), "dialog.ResponseLoadSuggests")
	proto.RegisterType((*RequestLoadMessageSuggests)(nil), "dialog.RequestLoadMessageSuggests")
	proto.RegisterType((*ResponseLoadMessageSuggests)(nil), "dialog.ResponseLoadMessageSuggests")
	proto.RegisterType((*RequestSendSuggestAction)(nil), "dialog.RequestSendSuggestAction")
}

func init() { proto.RegisterFile("suggests.proto", fileDescriptor_76389932d0fdfe60) }

var fileDescriptor_76389932d0fdfe60 = []byte{
	// 692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x3f, 0x4f, 0xdb, 0x4e,
	0x18, 0xce, 0x25, 0x10, 0xe2, 0x97, 0xff, 0x86, 0xdf, 0x8f, 0xd4, 0xc0, 0x29, 0x0a, 0x6a, 0x45,
	0xa5, 0xca, 0x44, 0xa0, 0x2e, 0x2c, 0x88, 0xb4, 0x55, 0x15, 0xa9, 0x48, 0xc8, 0x88, 0x0e, 0x1d,
	0x1a, 0x39, 0xf6, 0xe1, 0x5a, 0x75, 0x72, 0xae, 0xcf, 0x89, 0xc4, 0xc6, 0xd0, 0xa5, 0x4c, 0x1d,
	0xfb, 0x11, 0xfa, 0x09, 0xfa, 0x19, 0xda, 0x8d, 0x91, 0xb1, 0x98, 0xa5, 0x62, 0x62, 0xee, 0x54,
	0xd9, 0x77, 0x17, 0x12, 0xc7, 0x22, 0x4c, 0x51, 0x9e, 0xf7, 0xc9, 0xbd, 0xcf, 0xfb, 0xbc, 0x7f,
	0x02, 0x73, 0xac, 0xeb, 0x38, 0x84, 0x85, 0x4c, 0xf7, 0x03, 0x1a, 0x52, 0xb5, 0x68, 0xbb, 0xa6,
	0x47, 0x1d, 0x6d, 0xd5, 0xa1, 0xd4, 0xf1, 0xc8, 0x56, 0x82, 0xb6, 0xba, 0x27, 0x5b, 0xa4, 0xed,
	0x87, 0xa7, 0x9c, 0xa4, 0x2d, 0xda, 0xe4, 0xc4, 0xed, 0xb8, 0xa1, 0x4b, 0x3b, 0xe2, 0x77, 0xda,
	0xb4, 0x4f, 0x48, 0x20, 0xbf, 0xfc, 0xc7, 0x2c, 0xd3, 0x33, 0xfd, 0xd6, 0x96, 0xf8, 0xe4, 0x70,
	0xb5, 0x03, 0xf3, 0x07, 0x84, 0x31, 0xd3, 0x21, 0x47, 0x22, 0xa9, 0x5a, 0x03, 0x68, 0x73, 0xa8,
	0xe9, 0xda, 0x65, 0x54, 0x41, 0x9b, 0xd3, 0xdb, 0x8b, 0x3a, 0xd7, 0xa0, 0x1f, 0x1f, 0x37, 0x5e,
	0xbe, 0x35, 0xbd, 0x2e, 0x31, 0x14, 0x41, 0x6a, 0xd8, 0xea, 0x53, 0x58, 0x90, 0x92, 0x9b, 0xbe,
	0x79, 0xea, 0x51, 0xd3, 0x2e, 0xe7, 0x2b, 0x68, 0x53, 0x31, 0xe6, 0x25, 0x7e, 0xc8, 0xe1, 0xea,
	0x2f, 0x04, 0x73, 0xc7, 0xbe, 0x6d, 0x86, 0x77, 0xf9, 0x36, 0x60, 0xd2, 0xf2, 0xa8, 0xf5, 0x31,
	0x49, 0x55, 0xa8, 0xcf, 0x9e, 0xdf, 0xd4, 0x14, 0x98, 0xea, 0xb9, 0xcc, 0x6d, 0x79, 0xc4, 0xe0,
	0x31, 0xf5, 0x19, 0x80, 0x1f, 0x90, 0x5e, 0x93, 0x33, 0xf3, 0x59, 0x4c, 0x25, 0x26, 0xbc, 0x48,
	0xd8, 0x15, 0x98, 0x88, 0x6b, 0x2f, 0x17, 0x12, 0xf1, 0x33, 0x52, 0xfc, 0x21, 0x21, 0x81, 0x91,
	0x44, 0xd4, 0x3a, 0x2c, 0xc8, 0x22, 0xa5, 0xc4, 0xf2, 0x44, 0xc2, 0x5e, 0x91, 0xec, 0x94, 0x2f,
	0xc6, 0x7c, 0x7b, 0x18, 0xa8, 0x7e, 0x41, 0xb0, 0x64, 0x90, 0x4f, 0x5d, 0xc2, 0xc2, 0x37, 0xd4,
	0xb4, 0xfb, 0x05, 0xad, 0x03, 0x9c, 0x04, 0xb4, 0xdd, 0x1c, 0xa8, 0xca, 0x50, 0x62, 0x84, 0x8b,
	0x7b, 0x2e, 0xc4, 0xe5, 0x47, 0xc5, 0xd5, 0x97, 0x86, 0x4a, 0x3a, 0xbf, 0xa9, 0xe5, 0x17, 0x10,
	0x57, 0xbc, 0xbb, 0x16, 0xed, 0x3d, 0x82, 0x15, 0xb7, 0xad, 0xdb, 0x9e, 0xa3, 0x3b, 0x81, 0x6f,
	0xe9, 0xaf, 0x03, 0xdf, 0x12, 0xf9, 0xab, 0x3f, 0x10, 0x2c, 0x1b, 0x84, 0xf9, 0xb4, 0xc3, 0xc8,
	0x90, 0x98, 0x07, 0xb9, 0xbb, 0x03, 0xa5, 0xbe, 0x0b, 0xf9, 0x4a, 0xe1, 0x3e, 0x17, 0xfa, 0x44,
	0xf5, 0x31, 0xcc, 0xb5, 0x69, 0x40, 0x9a, 0x66, 0xcf, 0x74, 0x3d, 0xb3, 0xe5, 0x91, 0xc4, 0xee,
	0x92, 0x31, 0x1b, 0xa3, 0xfb, 0x12, 0xdc, 0x5d, 0x8f, 0xf6, 0x34, 0x28, 0x8f, 0xea, 0xe6, 0x5a,
	0xab, 0xdf, 0x10, 0x68, 0x03, 0x26, 0xa6, 0x87, 0x71, 0x53, 0x98, 0x85, 0x32, 0xcc, 0x2a, 0x0e,
	0xfa, 0xa3, 0x6e, 0xc3, 0xf4, 0xdd, 0xd8, 0xca, 0x32, 0x32, 0xe6, 0x16, 0xfa, 0x73, 0xcb, 0xc6,
	0x78, 0x7a, 0x86, 0x60, 0x75, 0xd0, 0xd3, 0xb4, 0xb6, 0xac, 0x19, 0x42, 0xf7, 0xbb, 0x97, 0x9e,
	0xa1, 0x71, 0xee, 0xfc, 0x45, 0x50, 0x16, 0x72, 0x8e, 0x48, 0x47, 0x76, 0x75, 0xdf, 0x8a, 0xd7,
	0x3c, 0x9e, 0xb3, 0x80, 0xc7, 0xe4, 0xa2, 0x16, 0x0c, 0x45, 0x20, 0x0d, 0x3b, 0x0e, 0x0b, 0x59,
	0x71, 0x98, 0xef, 0xa3, 0x22, 0x90, 0x86, 0x9d, 0x5a, 0xf3, 0xc2, 0x03, 0xd6, 0x5c, 0xf6, 0x62,
	0x62, 0x6c, 0x2f, 0x9e, 0xc0, 0x94, 0xbc, 0x03, 0x93, 0x71, 0xde, 0xfa, 0xcc, 0xf9, 0x4d, 0xad,
	0x04, 0xc5, 0x0f, 0xae, 0x6d, 0x93, 0x8e, 0x21, 0x83, 0xf7, 0xfb, 0xbf, 0xfd, 0x39, 0x0f, 0xa5,
	0xbe, 0xd9, 0x0d, 0x98, 0x19, 0x9a, 0xeb, 0x55, 0x99, 0x3e, 0x63, 0x03, 0xb5, 0xb5, 0xbb, 0x60,
	0xc6, 0x4a, 0xbc, 0x87, 0xa5, 0xac, 0x76, 0x56, 0x33, 0x5e, 0x4c, 0x71, 0xb4, 0x8d, 0xac, 0x87,
	0xd3, 0x0f, 0x1d, 0xc0, 0xe2, 0x68, 0xb3, 0x2a, 0xa9, 0xd7, 0x47, 0x18, 0xda, 0xff, 0x3a, 0xbf,
	0xef, 0xba, 0xbc, 0xef, 0xfa, 0xab, 0xf8, 0xbe, 0xd7, 0x8d, 0x8b, 0x2b, 0x9c, 0xbb, 0xbc, 0xc2,
	0xb9, 0xdb, 0x2b, 0x8c, 0xce, 0x22, 0x8c, 0xbe, 0x47, 0x18, 0xfd, 0x8c, 0x30, 0xba, 0x88, 0x30,
	0xfa, 0x1d, 0x61, 0xf4, 0x27, 0xc2, 0xb9, 0xdb, 0x08, 0xa3, 0xaf, 0xd7, 0x38, 0x77, 0x71, 0x8d,
	0x73, 0x97, 0xd7, 0x38, 0x07, 0xcb, 0x83, 0xae, 0x32, 0x12, 0xf4, 0x5c, 0x8b, 0xb0, 0x77, 0xe2,
	0xaf, 0xa4, 0x55, 0x4c, 0x72, 0xec, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xb0, 0x97, 0x52,
	0x6b, 0x06, 0x00, 0x00,
}

func (this *MessageSuggests) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MessageSuggests)
	if !ok {
		that2, ok := that.(MessageSuggests)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MessageId.Equal(that1.MessageId) {
		return false
	}
	if this.SuggestsPayload != that1.SuggestsPayload {
		return false
	}
	return true
}
func (this *UpdateSuggests) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpdateSuggests)
	if !ok {
		that2, ok := that.(UpdateSuggests)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Clock != that1.Clock {
		return false
	}
	if this.PrevClock != that1.PrevClock {
		return false
	}
	if !this.Peer.Equal(that1.Peer) {
		return false
	}
	if !this.MessageSuggests.Equal(that1.MessageSuggests) {
		return false
	}
	return true
}
func (this *RequestLoadSuggests) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestLoadSuggests)
	if !ok {
		that2, ok := that.(RequestLoadSuggests)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FromClock != that1.FromClock {
		return false
	}
	if !this.Peer.Equal(that1.Peer) {
		return false
	}
	return true
}
func (this *ResponseLoadSuggests) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseLoadSuggests)
	if !ok {
		that2, ok := that.(ResponseLoadSuggests)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Clock != that1.Clock {
		return false
	}
	if len(this.Suggests) != len(that1.Suggests) {
		return false
	}
	for i := range this.Suggests {
		if !this.Suggests[i].Equal(that1.Suggests[i]) {
			return false
		}
	}
	if this.MoreAvailable != that1.MoreAvailable {
		return false
	}
	return true
}
func (this *RequestLoadMessageSuggests) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestLoadMessageSuggests)
	if !ok {
		that2, ok := that.(RequestLoadMessageSuggests)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Peer.Equal(that1.Peer) {
		return false
	}
	if len(this.MessageIds) != len(that1.MessageIds) {
		return false
	}
	for i := range this.MessageIds {
		if !this.MessageIds[i].Equal(that1.MessageIds[i]) {
			return false
		}
	}
	return true
}
func (this *ResponseLoadMessageSuggests) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseLoadMessageSuggests)
	if !ok {
		that2, ok := that.(ResponseLoadMessageSuggests)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.MessageSuggests) != len(that1.MessageSuggests) {
		return false
	}
	for i := range this.MessageSuggests {
		if !this.MessageSuggests[i].Equal(that1.MessageSuggests[i]) {
			return false
		}
	}
	return true
}
func (this *RequestSendSuggestAction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestSendSuggestAction)
	if !ok {
		that2, ok := that.(RequestSendSuggestAction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RequestId != that1.RequestId {
		return false
	}
	if this.SuggestId != that1.SuggestId {
		return false
	}
	if !this.MessageId.Equal(that1.MessageId) {
		return false
	}
	if !this.Peer.Equal(that1.Peer) {
		return false
	}
	if this.Payload != that1.Payload {
		return false
	}
	return true
}
func (this *MessageSuggests) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&dialog.MessageSuggests{")
	if this.MessageId != nil {
		s = append(s, "MessageId: "+fmt.Sprintf("%#v", this.MessageId)+",\n")
	}
	s = append(s, "SuggestsPayload: "+fmt.Sprintf("%#v", this.SuggestsPayload)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UpdateSuggests) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&dialog.UpdateSuggests{")
	s = append(s, "Clock: "+fmt.Sprintf("%#v", this.Clock)+",\n")
	s = append(s, "PrevClock: "+fmt.Sprintf("%#v", this.PrevClock)+",\n")
	if this.Peer != nil {
		s = append(s, "Peer: "+fmt.Sprintf("%#v", this.Peer)+",\n")
	}
	if this.MessageSuggests != nil {
		s = append(s, "MessageSuggests: "+fmt.Sprintf("%#v", this.MessageSuggests)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestLoadSuggests) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&dialog.RequestLoadSuggests{")
	s = append(s, "FromClock: "+fmt.Sprintf("%#v", this.FromClock)+",\n")
	if this.Peer != nil {
		s = append(s, "Peer: "+fmt.Sprintf("%#v", this.Peer)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponseLoadSuggests) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&dialog.ResponseLoadSuggests{")
	s = append(s, "Clock: "+fmt.Sprintf("%#v", this.Clock)+",\n")
	if this.Suggests != nil {
		s = append(s, "Suggests: "+fmt.Sprintf("%#v", this.Suggests)+",\n")
	}
	s = append(s, "MoreAvailable: "+fmt.Sprintf("%#v", this.MoreAvailable)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestLoadMessageSuggests) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&dialog.RequestLoadMessageSuggests{")
	if this.Peer != nil {
		s = append(s, "Peer: "+fmt.Sprintf("%#v", this.Peer)+",\n")
	}
	if this.MessageIds != nil {
		s = append(s, "MessageIds: "+fmt.Sprintf("%#v", this.MessageIds)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponseLoadMessageSuggests) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&dialog.ResponseLoadMessageSuggests{")
	if this.MessageSuggests != nil {
		s = append(s, "MessageSuggests: "+fmt.Sprintf("%#v", this.MessageSuggests)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestSendSuggestAction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&dialog.RequestSendSuggestAction{")
	s = append(s, "RequestId: "+fmt.Sprintf("%#v", this.RequestId)+",\n")
	s = append(s, "SuggestId: "+fmt.Sprintf("%#v", this.SuggestId)+",\n")
	if this.MessageId != nil {
		s = append(s, "MessageId: "+fmt.Sprintf("%#v", this.MessageId)+",\n")
	}
	if this.Peer != nil {
		s = append(s, "Peer: "+fmt.Sprintf("%#v", this.Peer)+",\n")
	}
	s = append(s, "Payload: "+fmt.Sprintf("%#v", this.Payload)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSuggests(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SuggestsClient is the client API for Suggests service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuggestsClient interface {
	LoadSuggests(ctx context.Context, in *RequestLoadSuggests, opts ...grpc.CallOption) (*ResponseLoadSuggests, error)
	LoadMessageSuggests(ctx context.Context, in *RequestLoadMessageSuggests, opts ...grpc.CallOption) (*ResponseLoadMessageSuggests, error)
	SendSuggestAction(ctx context.Context, in *RequestSendSuggestAction, opts ...grpc.CallOption) (*types.Empty, error)
}

type suggestsClient struct {
	cc *grpc.ClientConn
}

func NewSuggestsClient(cc *grpc.ClientConn) SuggestsClient {
	return &suggestsClient{cc}
}

func (c *suggestsClient) LoadSuggests(ctx context.Context, in *RequestLoadSuggests, opts ...grpc.CallOption) (*ResponseLoadSuggests, error) {
	out := new(ResponseLoadSuggests)
	err := c.cc.Invoke(ctx, "/dialog.Suggests/LoadSuggests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suggestsClient) LoadMessageSuggests(ctx context.Context, in *RequestLoadMessageSuggests, opts ...grpc.CallOption) (*ResponseLoadMessageSuggests, error) {
	out := new(ResponseLoadMessageSuggests)
	err := c.cc.Invoke(ctx, "/dialog.Suggests/LoadMessageSuggests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suggestsClient) SendSuggestAction(ctx context.Context, in *RequestSendSuggestAction, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/dialog.Suggests/SendSuggestAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuggestsServer is the server API for Suggests service.
type SuggestsServer interface {
	LoadSuggests(context.Context, *RequestLoadSuggests) (*ResponseLoadSuggests, error)
	LoadMessageSuggests(context.Context, *RequestLoadMessageSuggests) (*ResponseLoadMessageSuggests, error)
	SendSuggestAction(context.Context, *RequestSendSuggestAction) (*types.Empty, error)
}

// UnimplementedSuggestsServer can be embedded to have forward compatible implementations.
type UnimplementedSuggestsServer struct {
}

func (*UnimplementedSuggestsServer) LoadSuggests(ctx context.Context, req *RequestLoadSuggests) (*ResponseLoadSuggests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadSuggests not implemented")
}
func (*UnimplementedSuggestsServer) LoadMessageSuggests(ctx context.Context, req *RequestLoadMessageSuggests) (*ResponseLoadMessageSuggests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMessageSuggests not implemented")
}
func (*UnimplementedSuggestsServer) SendSuggestAction(ctx context.Context, req *RequestSendSuggestAction) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSuggestAction not implemented")
}

func RegisterSuggestsServer(s *grpc.Server, srv SuggestsServer) {
	s.RegisterService(&_Suggests_serviceDesc, srv)
}

func _Suggests_LoadSuggests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLoadSuggests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestsServer).LoadSuggests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Suggests/LoadSuggests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestsServer).LoadSuggests(ctx, req.(*RequestLoadSuggests))
	}
	return interceptor(ctx, in, info, handler)
}

func _Suggests_LoadMessageSuggests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLoadMessageSuggests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestsServer).LoadMessageSuggests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Suggests/LoadMessageSuggests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestsServer).LoadMessageSuggests(ctx, req.(*RequestLoadMessageSuggests))
	}
	return interceptor(ctx, in, info, handler)
}

func _Suggests_SendSuggestAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSendSuggestAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestsServer).SendSuggestAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Suggests/SendSuggestAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestsServer).SendSuggestAction(ctx, req.(*RequestSendSuggestAction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Suggests_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dialog.Suggests",
	HandlerType: (*SuggestsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadSuggests",
			Handler:    _Suggests_LoadSuggests_Handler,
		},
		{
			MethodName: "LoadMessageSuggests",
			Handler:    _Suggests_LoadMessageSuggests_Handler,
		},
		{
			MethodName: "SendSuggestAction",
			Handler:    _Suggests_SendSuggestAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "suggests.proto",
}

func (m *MessageSuggests) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessageSuggests) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MessageSuggests) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SuggestsPayload) > 0 {
		i -= len(m.SuggestsPayload)
		copy(dAtA[i:], m.SuggestsPayload)
		i = encodeVarintSuggests(dAtA, i, uint64(len(m.SuggestsPayload)))
		i--
		dAtA[i] = 0x12
	}
	if m.MessageId != nil {
		{
			size, err := m.MessageId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSuggests(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateSuggests) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateSuggests) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateSuggests) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MessageSuggests != nil {
		{
			size, err := m.MessageSuggests.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSuggests(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Peer != nil {
		{
			size, err := m.Peer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSuggests(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.PrevClock != 0 {
		i = encodeVarintSuggests(dAtA, i, uint64(m.PrevClock))
		i--
		dAtA[i] = 0x10
	}
	if m.Clock != 0 {
		i = encodeVarintSuggests(dAtA, i, uint64(m.Clock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RequestLoadSuggests) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestLoadSuggests) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestLoadSuggests) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Peer != nil {
		{
			size, err := m.Peer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSuggests(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.FromClock != 0 {
		i = encodeVarintSuggests(dAtA, i, uint64(m.FromClock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ResponseLoadSuggests) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseLoadSuggests) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseLoadSuggests) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MoreAvailable {
		i--
		if m.MoreAvailable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Suggests) > 0 {
		for iNdEx := len(m.Suggests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Suggests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSuggests(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Clock != 0 {
		i = encodeVarintSuggests(dAtA, i, uint64(m.Clock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RequestLoadMessageSuggests) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestLoadMessageSuggests) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestLoadMessageSuggests) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageIds) > 0 {
		for iNdEx := len(m.MessageIds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageIds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSuggests(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Peer != nil {
		{
			size, err := m.Peer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSuggests(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResponseLoadMessageSuggests) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseLoadMessageSuggests) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseLoadMessageSuggests) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageSuggests) > 0 {
		for iNdEx := len(m.MessageSuggests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageSuggests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSuggests(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RequestSendSuggestAction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestSendSuggestAction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestSendSuggestAction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintSuggests(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Peer != nil {
		{
			size, err := m.Peer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSuggests(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.MessageId != nil {
		{
			size, err := m.MessageId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSuggests(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SuggestId) > 0 {
		i -= len(m.SuggestId)
		copy(dAtA[i:], m.SuggestId)
		i = encodeVarintSuggests(dAtA, i, uint64(len(m.SuggestId)))
		i--
		dAtA[i] = 0x12
	}
	if m.RequestId != 0 {
		i = encodeVarintSuggests(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSuggests(dAtA []byte, offset int, v uint64) int {
	offset -= sovSuggests(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MessageSuggests) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MessageId != nil {
		l = m.MessageId.Size()
		n += 1 + l + sovSuggests(uint64(l))
	}
	l = len(m.SuggestsPayload)
	if l > 0 {
		n += 1 + l + sovSuggests(uint64(l))
	}
	return n
}

func (m *UpdateSuggests) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Clock != 0 {
		n += 1 + sovSuggests(uint64(m.Clock))
	}
	if m.PrevClock != 0 {
		n += 1 + sovSuggests(uint64(m.PrevClock))
	}
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovSuggests(uint64(l))
	}
	if m.MessageSuggests != nil {
		l = m.MessageSuggests.Size()
		n += 1 + l + sovSuggests(uint64(l))
	}
	return n
}

func (m *RequestLoadSuggests) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FromClock != 0 {
		n += 1 + sovSuggests(uint64(m.FromClock))
	}
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovSuggests(uint64(l))
	}
	return n
}

func (m *ResponseLoadSuggests) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Clock != 0 {
		n += 1 + sovSuggests(uint64(m.Clock))
	}
	if len(m.Suggests) > 0 {
		for _, e := range m.Suggests {
			l = e.Size()
			n += 1 + l + sovSuggests(uint64(l))
		}
	}
	if m.MoreAvailable {
		n += 2
	}
	return n
}

func (m *RequestLoadMessageSuggests) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovSuggests(uint64(l))
	}
	if len(m.MessageIds) > 0 {
		for _, e := range m.MessageIds {
			l = e.Size()
			n += 1 + l + sovSuggests(uint64(l))
		}
	}
	return n
}

func (m *ResponseLoadMessageSuggests) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MessageSuggests) > 0 {
		for _, e := range m.MessageSuggests {
			l = e.Size()
			n += 1 + l + sovSuggests(uint64(l))
		}
	}
	return n
}

func (m *RequestSendSuggestAction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovSuggests(uint64(m.RequestId))
	}
	l = len(m.SuggestId)
	if l > 0 {
		n += 1 + l + sovSuggests(uint64(l))
	}
	if m.MessageId != nil {
		l = m.MessageId.Size()
		n += 1 + l + sovSuggests(uint64(l))
	}
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovSuggests(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovSuggests(uint64(l))
	}
	return n
}

func sovSuggests(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSuggests(x uint64) (n int) {
	return sovSuggests(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *MessageSuggests) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MessageSuggests{`,
		`MessageId:` + strings.Replace(fmt.Sprintf("%v", this.MessageId), "UUIDValue", "UUIDValue", 1) + `,`,
		`SuggestsPayload:` + fmt.Sprintf("%v", this.SuggestsPayload) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateSuggests) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateSuggests{`,
		`Clock:` + fmt.Sprintf("%v", this.Clock) + `,`,
		`PrevClock:` + fmt.Sprintf("%v", this.PrevClock) + `,`,
		`Peer:` + strings.Replace(fmt.Sprintf("%v", this.Peer), "Peer", "Peer", 1) + `,`,
		`MessageSuggests:` + strings.Replace(this.MessageSuggests.String(), "MessageSuggests", "MessageSuggests", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestLoadSuggests) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestLoadSuggests{`,
		`FromClock:` + fmt.Sprintf("%v", this.FromClock) + `,`,
		`Peer:` + strings.Replace(fmt.Sprintf("%v", this.Peer), "Peer", "Peer", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseLoadSuggests) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForSuggests := "[]*MessageSuggests{"
	for _, f := range this.Suggests {
		repeatedStringForSuggests += strings.Replace(f.String(), "MessageSuggests", "MessageSuggests", 1) + ","
	}
	repeatedStringForSuggests += "}"
	s := strings.Join([]string{`&ResponseLoadSuggests{`,
		`Clock:` + fmt.Sprintf("%v", this.Clock) + `,`,
		`Suggests:` + repeatedStringForSuggests + `,`,
		`MoreAvailable:` + fmt.Sprintf("%v", this.MoreAvailable) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestLoadMessageSuggests) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForMessageIds := "[]*UUIDValue{"
	for _, f := range this.MessageIds {
		repeatedStringForMessageIds += strings.Replace(fmt.Sprintf("%v", f), "UUIDValue", "UUIDValue", 1) + ","
	}
	repeatedStringForMessageIds += "}"
	s := strings.Join([]string{`&RequestLoadMessageSuggests{`,
		`Peer:` + strings.Replace(fmt.Sprintf("%v", this.Peer), "Peer", "Peer", 1) + `,`,
		`MessageIds:` + repeatedStringForMessageIds + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseLoadMessageSuggests) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForMessageSuggests := "[]*MessageSuggests{"
	for _, f := range this.MessageSuggests {
		repeatedStringForMessageSuggests += strings.Replace(f.String(), "MessageSuggests", "MessageSuggests", 1) + ","
	}
	repeatedStringForMessageSuggests += "}"
	s := strings.Join([]string{`&ResponseLoadMessageSuggests{`,
		`MessageSuggests:` + repeatedStringForMessageSuggests + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestSendSuggestAction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestSendSuggestAction{`,
		`RequestId:` + fmt.Sprintf("%v", this.RequestId) + `,`,
		`SuggestId:` + fmt.Sprintf("%v", this.SuggestId) + `,`,
		`MessageId:` + strings.Replace(fmt.Sprintf("%v", this.MessageId), "UUIDValue", "UUIDValue", 1) + `,`,
		`Peer:` + strings.Replace(fmt.Sprintf("%v", this.Peer), "Peer", "Peer", 1) + `,`,
		`Payload:` + fmt.Sprintf("%v", this.Payload) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringSuggests(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *MessageSuggests) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSuggests
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessageSuggests: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessageSuggests: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessageId == nil {
				m.MessageId = &UUIDValue{}
			}
			if err := m.MessageId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuggestsPayload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SuggestsPayload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSuggests(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateSuggests) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSuggests
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateSuggests: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateSuggests: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Clock", wireType)
			}
			m.Clock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Clock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevClock", wireType)
			}
			m.PrevClock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrevClock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &Peer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageSuggests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessageSuggests == nil {
				m.MessageSuggests = &MessageSuggests{}
			}
			if err := m.MessageSuggests.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSuggests(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestLoadSuggests) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSuggests
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestLoadSuggests: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestLoadSuggests: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromClock", wireType)
			}
			m.FromClock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FromClock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &Peer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSuggests(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseLoadSuggests) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSuggests
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseLoadSuggests: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseLoadSuggests: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Clock", wireType)
			}
			m.Clock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Clock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Suggests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Suggests = append(m.Suggests, &MessageSuggests{})
			if err := m.Suggests[len(m.Suggests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MoreAvailable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MoreAvailable = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipSuggests(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestLoadMessageSuggests) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSuggests
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestLoadMessageSuggests: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestLoadMessageSuggests: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &Peer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageIds = append(m.MessageIds, &UUIDValue{})
			if err := m.MessageIds[len(m.MessageIds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSuggests(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseLoadMessageSuggests) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSuggests
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseLoadMessageSuggests: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseLoadMessageSuggests: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageSuggests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageSuggests = append(m.MessageSuggests, &MessageSuggests{})
			if err := m.MessageSuggests[len(m.MessageSuggests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSuggests(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestSendSuggestAction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSuggests
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestSendSuggestAction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestSendSuggestAction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuggestId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SuggestId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessageId == nil {
				m.MessageId = &UUIDValue{}
			}
			if err := m.MessageId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &Peer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSuggests
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSuggests
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSuggests(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSuggests
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSuggests(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSuggests
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSuggests
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSuggests
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSuggests
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSuggests
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSuggests        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSuggests          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSuggests = fmt.Errorf("proto: unexpected end of group")
)
